services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tmpfs:
      - /var/lib/mysql
